apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig-secret
  namespace: default
data:
  config: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTVRJM01EY3lNVEl3SGhjTk1qUXdOREV3TURBd01ERXlXaGNOTXpRd05EQTRNREF3TURFeQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTVRJM01EY3lNVEl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRVlVYdEtjdnl6R1NMMkFZWTJvU3dYYk9PbDIyckpXam50T2dlUzgzUlEKd1dWOFFSSlZheitSclJXTXk2azR1YTNNY3JGTzdhNU95cVFXMmlITng0WHVvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXJzY0hyM1h5dG5CcitzVHhMZldoCkRPZXJRR1V3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUxONE56cHNyaVo4SmNCUjlabzdoMnVXekk3TFlFczMKNGppcU9pQm00N1hOQWlFQXBKQzRTNE1XNEYyQjM0OW8rVEQ2NXpEdXh6ckJ2enYvdUR2RlVrY01FaDA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
